# Generated by Django 3.0.5 on 2020-04-30 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='id',
        ),
        migrations.AlterField(
            model_name='film',
            name='dataset_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Film', unique=True),
        ),
    ]
