# Generated by Django 3.0.5 on 2020-05-02 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0003_auto_20200430_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Film'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('film', 'user')},
        ),
    ]
