# Generated by Django 3.0.5 on 2020-05-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200505_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
