# Generated by Django 3.0.5 on 2020-05-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200510_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='mean_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
