# Generated by Django 3.0.5 on 2020-06-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_film_mean_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
