# Generated by Django 3.0.8 on 2020-12-07 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0011_recommendations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendations',
            name='id',
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recommendations', serialize=False, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
