# Generated by Django 3.1.4 on 2020-12-31 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20201207_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarItems',
            fields=[
                ('similar_items', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('film', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='similar_items', serialize=False, to='backend.film', unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='recommendations',
            field=models.JSONField(),
        ),
    ]
